package org.isc.certanalysis.domain;
// Generated Jan 25, 2019 9:50:29 AM by Hibernate Tools 4.3.5.Final

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import java.time.Instant;
import java.time.LocalDateTime;

/**
 * CrlRevoked generated by hbm2java
 */
@Entity
@Table(name = "CRL_REVOKED", schema = "CERT_REP3")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class CrlRevoked extends AbstractAuditingEntity {

	private long id;
	private Crl crl;
	private LocalDateTime revocationDate;
	private String serialNumber;
	private short reasonCode;

	public CrlRevoked() {
		super();
	}

	public CrlRevoked(long id, Crl crl, LocalDateTime revocationDate, String serialNumber, short reasonCode, String createdBy,
	                  Instant createdDate, String lastModifiedBy, Instant lastModifiedDate) {
		super(createdBy, createdDate, lastModifiedBy, lastModifiedDate);
		this.id = id;
		this.crl = crl;
		this.revocationDate = revocationDate;
		this.serialNumber = serialNumber;
		this.reasonCode = reasonCode;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CRL_REVOKED_SEQ")
	@SequenceGenerator(sequenceName = "SEQ_CRL_REVOKED", name = "CRL_REVOKED_SEQ", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRL_ID", nullable = false)
	public Crl getCrl() {
		return this.crl;
	}

	public void setCrl(Crl crl) {
		this.crl = crl;
	}

//	@Temporal(TemporalType.DATE)
	@Column(name = "REVOCATION_DATE", nullable = false, length = 7)
	public LocalDateTime getRevocationDate() {
		return this.revocationDate;
	}

	public void setRevocationDate(LocalDateTime revocationDate) {
		this.revocationDate = revocationDate;
	}

	@Column(name = "SERIAL_NUMBER", nullable = false, length = 48)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "REASON_CODE", nullable = false, precision = 3, scale = 0)
	public short getReasonCode() {
		return this.reasonCode;
	}

	public void setReasonCode(short reasonCode) {
		this.reasonCode = reasonCode;
	}

	@Override
	public int hashCode() {
		return 31;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (!(o instanceof CrlRevoked)) return false;
		return getId() != null && getId().equals(((CrlRevoked) o).getId());
	}

}
