package org.isc.certanalysis.domain;
// Generated Jan 25, 2019 9:50:29 AM by Hibernate Tools 4.3.5.Final

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name = "PRIVILEGE", schema = "CERT_REP3")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Privilege implements java.io.Serializable {

	private long id;
	private String name;
	private Set<Role> roles = new HashSet<Role>(0);

	public Privilege() {
	}

	public Privilege(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Privilege(long id, String name, Set<Role> roles) {
		this.id = id;
		this.name = name;
		this.roles = roles;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 24)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "privileges")
	/*@JoinTable(name = "ROLE_PRIVILEGE", schema = "CERT_REP3", joinColumns = {
			@JoinColumn(name = "PRIVILEGE_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) })*/
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
